import { GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import SinglePost from '../components/Post/SinglePost'
import Tag from '../components/Tag/Tag'
import { getAllTags, getPostsForTopPage } from '../lib/notionAPI'

export const getStaticProps: GetStaticProps = async () => {
  const fourPosts = await getPostsForTopPage(4)
  const allTags = await getAllTags()

  return {
    props: {
      fourPosts,
      allTags,
    },
    revalidate: 10,
  }
}

export default function Home({ fourPosts, allTags }) {
  return (
    <div className="container mx-auto h-full w-full">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mt-16 w-full">
        <h1 className="mb-16 text-center text-5xl font-medium">
          Notion Blog🚀
        </h1>
        {fourPosts.map((post) => (
          <div className="mx-4" key={post.id}>
            <SinglePost
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
              isPaginationPage={false}
            />
          </div>
        ))}
        <Link
          href="/posts/page/1"
          className="mx-auto mb-6 block px-5 text-right lg:w-1/2"
        >
          ...もっと見る
        </Link>
        <Tag tags={allTags} />
      </main>
    </div>
  )
}
